# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://pmoskovi.github.io/kaazing-developer-network"
# url: http://localhost:4000
# Build settings
markdown: kramdown
permalink: pretty
categories: [products industries]
